language: python
python:
  - "3.5"
  - "3.6"
# Command to install dependencies
install:
  - pip install .
# Check formatting
script:
  - $(autopep8 --diff $(find docs -regex ".*\.py"))
  - $(autopep8 --diff $(find hep_rfm -regex ".*\.py"))
  - $(autopep8 --diff $(find scripts -regex ".*\.py"))
  - $(autopep8 --diff $(find tests -regex ".*\.py"))
# Command to run tests
script:
  - pytest -v tests